/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import modelo.Central;

public class Ranking extends javax.swing.JFrame {

    Menu menu = new Menu();

    /**
     * Creates new form Rankig
     */
    public Ranking() {
        initComponents();
        if(Central.rankingPontos().get(1).getLogin() == null){
            pu2.setText("Nao Exite");
        }
        if(Central.rankingPontos().get(2).getLogin() == null){
            pu2.setText("Nao Exite");
        }
        if(String.valueOf(Central.rankingPontos().get(0).getPontos()) == null){
            pu3.setText("Nao Exite");
        }
        if(String.valueOf(Central.rankingPontos().get(0).getPontos()) == null){
            pu3.setText("Nao Exite");
        }
        pu1.setText(Central.rankingPontos().get(0).getLogin());
        pu2.setText(Central.rankingPontos().get(1).getLogin());
        pu3.setText(Central.rankingPontos().get(2).getLogin());
        pp1.setText(String.valueOf(Central.rankingPontos().get(0).getPontos()));
        pp2.setText(String.valueOf(Central.rankingPontos().get(1).getPontos()));
        pp3.setText(String.valueOf(Central.rankingPontos().get(2).getPontos()));

        vu1.setText(Central.rankingVitorias().get(0).getLogin());
        vu2.setText(Central.rankingVitorias().get(1).getLogin());
        vu3.setText(Central.rankingVitorias().get(2).getLogin());
        vp1.setText(String.valueOf(Central.rankingVitorias().get(0).getVitorias()));
        vp2.setText(String.valueOf(Central.rankingVitorias().get(1).getVitorias()));
        vp3.setText(String.valueOf(Central.rankingVitorias().get(2).getVitorias()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        b_voltar = new javax.swing.JButton();
        rPontos = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        pontuacao = new javax.swing.JLabel();
        lp1 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        lp3 = new javax.swing.JLabel();
        pu1 = new javax.swing.JLabel();
        pu2 = new javax.swing.JLabel();
        pu3 = new javax.swing.JLabel();
        pp1 = new javax.swing.JLabel();
        pp2 = new javax.swing.JLabel();
        pp3 = new javax.swing.JLabel();
        rVitorias = new javax.swing.JPanel();
        vusuario = new javax.swing.JLabel();
        vitorias = new javax.swing.JLabel();
        lv1 = new javax.swing.JLabel();
        lv2 = new javax.swing.JLabel();
        lv3 = new javax.swing.JLabel();
        vu1 = new javax.swing.JLabel();
        vu2 = new javax.swing.JLabel();
        vu3 = new javax.swing.JLabel();
        vp1 = new javax.swing.JLabel();
        vp2 = new javax.swing.JLabel();
        vp3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dadosConta = new javax.swing.JMenuItem();
        escluirConta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sairConta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        listar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC TAC TOE");
        setResizable(false);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_voltar.setText("Voltar");
        b_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_voltarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(b_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        rPontos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ranking por Pontos"));

        usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario.setText("Usuário");

        pontuacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pontuacao.setText("Pontuação");

        lp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lp1.setText("#1");

        lp2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lp2.setText("#2");

        lp3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lp3.setText("#3");

        pu1.setText("Usuário 1");

        pu2.setText("Usuário 2");

        pu3.setText("Usuário 3");

        pp1.setText("Pontos 1");

        pp2.setText("Pontos 2");

        pp3.setText("Pontos 3");

        javax.swing.GroupLayout rPontosLayout = new javax.swing.GroupLayout(rPontos);
        rPontos.setLayout(rPontosLayout);
        rPontosLayout.setHorizontalGroup(
            rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rPontosLayout.createSequentialGroup()
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rPontosLayout.createSequentialGroup()
                        .addComponent(lp3)
                        .addGap(18, 18, 18)
                        .addComponent(pu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rPontosLayout.createSequentialGroup()
                        .addComponent(lp2)
                        .addGap(18, 18, 18)
                        .addComponent(pu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rPontosLayout.createSequentialGroup()
                        .addComponent(lp1)
                        .addGap(18, 18, 18)
                        .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario)
                            .addComponent(pu1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pontuacao)
                    .addComponent(pp1)
                    .addComponent(pp2)
                    .addComponent(pp3))
                .addGap(25, 25, 25))
        );
        rPontosLayout.setVerticalGroup(
            rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rPontosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(pontuacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lp1)
                    .addComponent(pu1)
                    .addComponent(pp1))
                .addGap(18, 18, 18)
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lp2)
                    .addComponent(pu2)
                    .addComponent(pp2))
                .addGap(18, 18, 18)
                .addGroup(rPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lp3)
                    .addComponent(pu3)
                    .addComponent(pp3))
                .addGap(55, 55, 55))
        );

        jLayeredPane1.add(rPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 260, 230));

        rVitorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Ranking por Vitórias"));

        vusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vusuario.setText("Usuário");

        vitorias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vitorias.setText("Vitórias");

        lv1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lv1.setText("#1");

        lv2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lv2.setText("#2");

        lv3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lv3.setText("#3");

        vu1.setText("Usuário 1");

        vu2.setText("Usuário 2");

        vu3.setText("Usuário 3");

        vp1.setText("Pontos 1");

        vp2.setText("Pontos 2");

        vp3.setText("Pontos 3");

        javax.swing.GroupLayout rVitoriasLayout = new javax.swing.GroupLayout(rVitorias);
        rVitorias.setLayout(rVitoriasLayout);
        rVitoriasLayout.setHorizontalGroup(
            rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rVitoriasLayout.createSequentialGroup()
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rVitoriasLayout.createSequentialGroup()
                        .addComponent(lv3)
                        .addGap(18, 18, 18)
                        .addComponent(vu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rVitoriasLayout.createSequentialGroup()
                        .addComponent(lv2)
                        .addGap(18, 18, 18)
                        .addComponent(vu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rVitoriasLayout.createSequentialGroup()
                        .addComponent(lv1)
                        .addGap(18, 18, 18)
                        .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vusuario)
                            .addComponent(vu1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vitorias)
                    .addComponent(vp1)
                    .addComponent(vp2)
                    .addComponent(vp3))
                .addGap(25, 25, 25))
        );
        rVitoriasLayout.setVerticalGroup(
            rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rVitoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vusuario)
                    .addComponent(vitorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lv1)
                    .addComponent(vu1)
                    .addComponent(vp1))
                .addGap(18, 18, 18)
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lv2)
                    .addComponent(vu2)
                    .addComponent(vp2))
                .addGap(18, 18, 18)
                .addGroup(rVitoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lv3)
                    .addComponent(vu3)
                    .addComponent(vp3))
                .addGap(55, 55, 55))
        );

        jLayeredPane1.add(rVitorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 260, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1 (1).jpg"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, -1));

        jMenu1.setText("Conta");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        dadosConta.setText("Dados da conta");
        dadosConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadosContaMouseClicked(evt);
            }
        });
        dadosConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosContaActionPerformed(evt);
            }
        });
        jMenu1.add(dadosConta);

        escluirConta.setText("Excluir conta");
        escluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escluirContaActionPerformed(evt);
            }
        });
        jMenu1.add(escluirConta);
        jMenu1.add(jSeparator1);

        sairConta.setText("Sair da conta");
        sairConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairContaActionPerformed(evt);
            }
        });
        jMenu1.add(sairConta);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Listar");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        listar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listar.setText("Listar jogadores");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        jMenu3.add(listar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        setSize(new java.awt.Dimension(720, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_voltarActionPerformed
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_b_voltarActionPerformed

    private void dadosContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosContaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosContaMouseClicked

    private void dadosContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosContaActionPerformed
        DadosConta tela = new DadosConta();
        tela.setVisible(true);
    }//GEN-LAST:event_dadosContaActionPerformed

    private void escluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escluirContaActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir sua conta permanetemente? ", "Confirme", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            Central.removerJogador();
            JOptionPane.showMessageDialog(this, "Sua conta foi excluída permanentemente.");
            TelaInicial tela = new TelaInicial();
            this.dispose();
            tela.setVisible(true);
        }
    }//GEN-LAST:event_escluirContaActionPerformed

    private void sairContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairContaActionPerformed
        dispose();
        TelaInicial login = new TelaInicial();
        login.setVisible(true);
    }//GEN-LAST:event_sairContaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        ListarJogadores listar = new ListarJogadores(this, true);
        listar.setVisible(true);
    }//GEN-LAST:event_listarActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_voltar;
    private javax.swing.JMenuItem dadosConta;
    private javax.swing.JMenuItem escluirConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listar;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    private javax.swing.JLabel lp3;
    private javax.swing.JLabel lv1;
    private javax.swing.JLabel lv2;
    private javax.swing.JLabel lv3;
    private javax.swing.JLabel pontuacao;
    private javax.swing.JLabel pp1;
    private javax.swing.JLabel pp2;
    private javax.swing.JLabel pp3;
    private javax.swing.JLabel pu1;
    private javax.swing.JLabel pu2;
    private javax.swing.JLabel pu3;
    private javax.swing.JPanel rPontos;
    private javax.swing.JPanel rVitorias;
    private javax.swing.JMenuItem sairConta;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel vitorias;
    private javax.swing.JLabel vp1;
    private javax.swing.JLabel vp2;
    private javax.swing.JLabel vp3;
    private javax.swing.JLabel vu1;
    private javax.swing.JLabel vu2;
    private javax.swing.JLabel vu3;
    private javax.swing.JLabel vusuario;
    // End of variables declaration//GEN-END:variables
}
